### ISSUE TITLE
Future updates?

### ISSUE THREAD

**Issue by JoniVR** [MatijaKruljac/VerticalCardSwitcher#1]
Hi, 
I really liked this library, are there any plans to update this in the future? 
Currently it's missing some things in my opinion: 
- Autolayout/storyboard support
- Scroll through multiple cards at once (still paged, but faster scrolling = more cards being scrolled)
- Sliding to next card by sliding on the current one

I'd be happy to even donate some money for this as it would help me out a lot!

Thankyou for your awesome work!

**Comment by MatijaKruljac** [comment]
Hi @JoniVR , 
I agree with everything you said. I've planned to add those updates in the library from the beginning, but currently I'm little short with time. It will be implemented for sure in the near future. 

I'm happy to help.

**Comment by JoniVR** [comment]
@MatijaKruljac Sounds great! Looking forward to it 😊
Also, you should definitely consider placing a donation link or something, just in case 😝
